# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: clone
        run: |
          cd ..
          git clone https://github.com/starwild/page docs
          cd -

      # Runs a single command using the runners shell
      - name: build
        run: bash run.sh -b

      # push docs
#       - name: push
#         run: |
#           cd ../docs
#           git config --global user.email "${{github.repository_owner}}@github.com"
#           git config --global user.name "${{github.repository_owner}}"
#           git config --global user.password "${{secrets.GITHUB_TOKEN}}"
#           git add .
#           git commit -m "build $(date +%Y-%m-%d\ %H:%M:%S)" -a
#           git push https://${{github.repository_owner}}:${{secrets.MY_KEY}}@github.com/starwild/page
#           cd -

      - name: Git Push Action
        # You may pin to the exact commit or the version.
        # uses: x-actions/git-push@fa7affbdc76b1c598c8337f9b830ea11c6d13d70
        uses: x-actions/git-push@v1
        with:
          # git user email
          GITHUB_EMAIL: ${{github.repository_owner}}@github.com # optional, default is xiexianbin
          # git use username
          GITHUB_USERNAME: ${{github.repository_owner}} # optional, default is me@xiexianbin.cn
          # https:/<token>@github.com/owner/repo.git
          PUBLISH_REPO: https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository_owner}}/${{github.repository_owner}}.github.io.git # optional
          # git branch
          PUBLISH_BRANCH: main # optional
          # dir to publish
          PUBLISH_DIR: ../docs # optional
